FROM alpine

ARG TARGETARCH

RUN apk update \
    && apk upgrade \
    && apk add --no-cache ca-certificates tzdata \
    && update-ca-certificates 2>/dev/null || true

COPY go-template-$TARGETARCH /go-template
EXPOSE 3000
WORKDIR /data
ENTRYPOINT ["/go-template"]
